// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8fyitiKjViEs9OZ5MCyC97GH-kh30_bc',
    appId: '1:190244829616:web:241f6b6932755a2ddbbe75',
    messagingSenderId: '190244829616',
    projectId: 'finalprojectasupro',
    authDomain: 'finalprojectasupro.firebaseapp.com',
    storageBucket: 'finalprojectasupro.firebasestorage.app',
    measurementId: 'G-YRD7KY8E5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx5vhpt8JAM3r6SmUDxYo8WQWw43CMFig',
    appId: '1:190244829616:android:86c0b1eaf2564ff3dbbe75',
    messagingSenderId: '190244829616',
    projectId: 'finalprojectasupro',
    storageBucket: 'finalprojectasupro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaLasLHbPLaFppsKEeh9YvjCB1K2vmcJY',
    appId: '1:190244829616:ios:16c7a99cd8728759dbbe75',
    messagingSenderId: '190244829616',
    projectId: 'finalprojectasupro',
    storageBucket: 'finalprojectasupro.firebasestorage.app',
    iosBundleId: 'com.example.asuMessengerPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaLasLHbPLaFppsKEeh9YvjCB1K2vmcJY',
    appId: '1:190244829616:ios:16c7a99cd8728759dbbe75',
    messagingSenderId: '190244829616',
    projectId: 'finalprojectasupro',
    storageBucket: 'finalprojectasupro.firebasestorage.app',
    iosBundleId: 'com.example.asuMessengerPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8fyitiKjViEs9OZ5MCyC97GH-kh30_bc',
    appId: '1:190244829616:web:a13671fe17de71b0dbbe75',
    messagingSenderId: '190244829616',
    projectId: 'finalprojectasupro',
    authDomain: 'finalprojectasupro.firebaseapp.com',
    storageBucket: 'finalprojectasupro.firebasestorage.app',
    measurementId: 'G-FJG1MK0GS3',
  );

}